import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, of } from 'rxjs';

@Injectable({ providedIn: 'root' })
export class DashboardService {
    private apiUrl =
        'https://test.ewanhr.com/BroaERP.BusinessSector.API/Receivables/CustomerBalance/GetDetailsPage?id=98&contractId=All';

    constructor(private http: HttpClient) {}

    getDashboardData(useMock: boolean = true): Observable<any> {
        if (useMock) {
            const mockData = {
                IsSuccess: true,
                Message: null,
                AdditionalInfo: null,
                Data: {
                    CustomerBalanceVM: {
                        Id: 98,
                        Code: 'EBS010000104',
                        CustomerTypeId: null,
                        CustomerTypeArabicName: null,
                        Name: 'شركة إي اف أس أي أم لإدارة المرافق',
                        PhoneNumber: null,
                        UnifiedBankAccountNumber: null,
                        IsInactive: false,
                        DiscountRatio: 0.0,
                        DebitBalance: 18165116.9,
                        CreditBalance: 14089118.81,
                        CurrentBalance: 4075998.09,
                        InitialBalance: 1635904.81,
                        TotalBalance: 5711902.9,
                    },
                    CreditGridItemsVM: [
                        {
                            CreditReceivableId: '240400005785',
                            CreditReceivableTypeId: 'PR',
                            CreditReceivableTypeName: 'سند قبض',
                            DocumentDate: '2024-04-23T00:00:00',
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            NetValue: 1635904.86,
                            TolalPaid: 0.0,
                            StatusId: '005',
                        },
                        {
                            CreditReceivableId: '240500002670',
                            CreditReceivableTypeId: 'PR',
                            CreditReceivableTypeName: 'سند قبض',
                            DocumentDate: '2024-05-01T00:00:00',
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            NetValue: 175247.5,
                            TolalPaid: 0.0,
                            StatusId: '005',
                        },
                        {
                            CreditReceivableId: '240500006207',
                            CreditReceivableTypeId: 'PR',
                            CreditReceivableTypeName: 'سند قبض',
                            DocumentDate: '2024-05-15T00:00:00',
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            NetValue: 988726.25,
                            TolalPaid: 0.0,
                            StatusId: '005',
                        },
                        {
                            CreditReceivableId: '240600004172',
                            CreditReceivableTypeId: 'PR',
                            CreditReceivableTypeName: 'سند قبض',
                            DocumentDate: '2024-06-06T00:00:00',
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            NetValue: 1804236.63,
                            TolalPaid: 0.0,
                            StatusId: '005',
                        },
                        {
                            CreditReceivableId: '240700002633',
                            CreditReceivableTypeId: 'PR',
                            CreditReceivableTypeName: 'سند قبض',
                            DocumentDate: '2024-07-04T00:00:00',
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            NetValue: 1714135.06,
                            TolalPaid: 0.0,
                            StatusId: '005',
                        },
                        {
                            CreditReceivableId: '240800001296',
                            CreditReceivableTypeId: 'PR',
                            CreditReceivableTypeName: 'سند قبض',
                            DocumentDate: '2024-07-16T00:00:00',
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            NetValue: 690803.95,
                            TolalPaid: 0.0,
                            StatusId: '005',
                        },
                        {
                            CreditReceivableId: '240800001567',
                            CreditReceivableTypeId: 'PR',
                            CreditReceivableTypeName: 'سند قبض',
                            DocumentDate: '2024-07-16T00:00:00',
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            NetValue: 315150.5,
                            TolalPaid: 0.0,
                            StatusId: '005',
                        },
                        {
                            CreditReceivableId: '240800005223',
                            CreditReceivableTypeId: 'PR',
                            CreditReceivableTypeName: 'سند قبض',
                            DocumentDate: '2024-08-04T00:00:00',
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            NetValue: 1720835.3,
                            TolalPaid: 0.0,
                            StatusId: '005',
                        },
                        {
                            CreditReceivableId: '240900001869',
                            CreditReceivableTypeId: 'PR',
                            CreditReceivableTypeName: 'سند قبض',
                            DocumentDate: '2024-08-28T00:00:00',
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            NetValue: 1000000.0,
                            TolalPaid: 0.0,
                            StatusId: '005',
                        },
                        {
                            CreditReceivableId: '240900003936',
                            CreditReceivableTypeId: 'PR',
                            CreditReceivableTypeName: 'سند قبض',
                            DocumentDate: '2024-09-04T00:00:00',
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            NetValue: 804474.95,
                            TolalPaid: 0.0,
                            StatusId: '005',
                        },
                        {
                            CreditReceivableId: '240900003918',
                            CreditReceivableTypeId: 'PR',
                            CreditReceivableTypeName: 'سند قبض',
                            DocumentDate: '2024-09-04T00:00:00',
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            NetValue: 560181.4,
                            TolalPaid: 0.0,
                            StatusId: '005',
                        },
                        {
                            CreditReceivableId: '241000003211',
                            CreditReceivableTypeId: 'PR',
                            CreditReceivableTypeName: 'سند قبض',
                            DocumentDate: '2024-10-03T00:00:00',
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            NetValue: 1679422.41,
                            TolalPaid: 0.0,
                            StatusId: '005',
                        },
                        {
                            CreditReceivableId: '241000004100',
                            CreditReceivableTypeId: 'PR',
                            CreditReceivableTypeName: 'سند قبض',
                            DocumentDate: '2024-10-14T00:00:00',
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            NetValue: 1000000.0,
                            TolalPaid: 0.0,
                            StatusId: '005',
                        },
                    ],
                    DebitGridItemsVM: [
                        {
                            DebitId: '24040000670',
                            DocumentDate: '2024-03-31T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 286196.2,
                        },
                        {
                            DebitId: '24050000996',
                            DocumentDate: '2024-05-01T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 1804236.62,
                        },
                        {
                            DebitId: '24050004864',
                            DocumentDate: '2024-05-06T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 142485.0,
                        },
                        {
                            DebitId: '24050005412',
                            DocumentDate: '2024-05-07T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 702530.05,
                        },
                        {
                            DebitId: '24050007664',
                            DocumentDate: '2024-05-12T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 3622.5,
                        },
                        {
                            DebitId: '24060001913',
                            DocumentDate: '2024-06-03T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 1714135.06,
                        },
                        {
                            DebitId: '24060003922',
                            DocumentDate: '2024-06-09T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 690803.95,
                        },
                        {
                            DebitId: '24060008494',
                            DocumentDate: '2024-06-27T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 1720835.07,
                        },
                        {
                            DebitId: '24060009729',
                            DocumentDate: '2024-06-30T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 759816.95,
                        },
                        {
                            DebitId: '24070008264',
                            DocumentDate: '2024-07-30T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 1874803.25,
                        },
                        {
                            DebitId: '24080001145',
                            DocumentDate: '2024-08-04T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 804474.95,
                        },
                        {
                            DebitId: '24080008550',
                            DocumentDate: '2024-08-28T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 1730315.78,
                        },
                        {
                            DebitId: '24090001324',
                            DocumentDate: '2024-09-04T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 804797.4,
                        },
                        {
                            DebitId: '24100000164',
                            DocumentDate: '2024-10-01T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 1642722.42,
                        },
                        {
                            DebitId: '24100000591',
                            DocumentDate: '2024-10-02T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 871810.45,
                        },
                        {
                            DebitId: '24100002211',
                            DocumentDate: '2024-10-06T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 150686.8,
                        },
                        {
                            DebitId: '24100008264',
                            DocumentDate: '2024-10-30T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 1559673.65,
                        },
                        {
                            DebitId: '24110000746',
                            DocumentDate: '2024-11-03T00:00:00',
                            RefNumber: null,
                            CustomerId: 98,
                            ContractId: 99,
                            ContractCode: 'EBS010000104',
                            CustomerCode: 'EBS010000104',
                            DebitReceivableTypeId: 'CR',
                            DebitReceivableTypeName: 'فاتورة آجلة',
                            NetValue: 901170.8,
                        },
                    ],
                },
                FailedReason: null,
            };
            return of(mockData);
        } else {
            return this.http.get<any>(this.apiUrl);
        }
    }
}
